@startuml
|FEngineLoop|
start
:tick;
:FPlatformApplicationMisc::PumpMessages(true);
|[global]|
:WinPumpMessages();

|FWindowsApplication|
:AppWndProc;
|[global]|
:WindowsApplication_WndProc;
|FWindowsApplication|
:ProcessMessage;
:DeferMessage;
:ProcessDeferredMessage;
|FSlateApplication|
:OnMouseDown;
:ProcessMouseButtonDownEvent;
:LocateWindowUnderMouse;
:LocateWindowUnderMouse(ScreenspaceMouseCoordinate, Window->GetChildWindows(), bIgnoreEnabledStatus);
-[dashed]->
:LocateWidgetInWindow;
|FHittestGrid|
:GetBubblePath;
-[dashed]->
|FSlateApplication|
:RoutePointerDownEvent;
|FEventRouter|
:Route<FReply>;
|FSlateApplication|
:[this]( const FArrangedWidget TargetWidget, const FPointerEvent& Event );
|SViewport|
:OnMouseButtonDown;
|FSceneViewport|
:OnMouseButtonDown;
|FViewportClient|
:InputKey;
|APlayerController|
:InputKey;
|UPlayerInput|
:InputKey;

stop
@enduml