@startuml

|World|
:SpawnActor;
|AActor|
:PostSpawnInitialize;
:RegisterAllComponents;
:IncrementalRegisterComponents;
|UActorCompoenent|
:RegisterComponentWithWorld;
:ExecuteRegisterEvents;
|UPrimitiveCompoenent|
:CreateRenderState_Concurrent;
|FScene|
:AddPrimitive;
|UPrimitiveCompoenent|
:CreateSceneProxy;
|FScene|
:Primitive->SceneProxy = PrimitiveSceneProxy;
end

@enduml