@startuml
|main|
start
if(IsEditor) then (yes)
|UEditorEngine|
:Tick;
:StarQueuedPlaySessionRequest;
#palegreen:CreateInnerProcessPIEGameInstance;
|UGameInstance|
#AntiqueWhite:InitializeForPlayInEditor;
:Init;
note right
create UOnlineSession 
and register delegetes
end note
|UEditorEngine|
-[#AntiqueWhite,dashed]-> 
:PostCreatePIEWorld;
|UWorld|
:InitWorld;
|UGameInstance|
-[#palegreen,dashed]-> 
#LightCoral:StartPlayInEditorGameInstance;
|UWorld|
:SetGameMode;
|UGameInstance|
:CreateGameModeForURL;
|UWorld|
-[#LightCoral,dashed]-> 
:InitializeActorsForPlay;
|ULocalPlayer|
:SpawnPlayActor;
note right
create playercontroller
login when local server
end note

|UWorld|
-[#LightCoral,dashed]-> 
:BeginPlay;
|AGameModeBase|
:StartPlay;
|AGameStateBase|
:HandleBeginPlay;
|AWorldSettings|
:NotifyBeginPlay;
|UWorld|
:SetBegunPlay;
else(no)
|FEngineLoop|
#DeepPink:Init;
|UGameEngine|
:Init;
|UGameInstance|
#YellowGreen:InitializeStandalone;
|UWorld|
:CreateWorld;
:InitializeNewWorld;
:InitWorld;
-[#YellowGreen,dashed]-> 
:SetGameInstance;
|UGameInstance|
-[#YellowGreen,dashed]-> 
:Init;
|UGameEngine|
-[#DeepPink,dashed]-> 
:Start;
|UGameInstance|
:StartGameInstance;
|UEngine|
:Browse;
#SteelBlue:LoadMap;
note right
spawn actors
end note
|UWorld|
:SetGameMode;
-[#SteelBlue,dashed]-> 
:InitializeActorsForPlay;
|ULocalPlayer|
-[#SteelBlue,dashed]-> 
:SpawnPlayActor;
|UWorld|
-[#SteelBlue,dashed]-> 
:BeginPlay;
|AGameModeBase|
:StartPlay;
|AGameStateBase|
:HandleBeginPlay;
|AWorldSettings|
:NotifyBeginPlay;
|UWorld|
:SetBegunPlay;
endif
end
@enduml