@startuml RenderCore


class FShaderResource 
note top
Compiled shader bytecode and its corresponding RHI resource. 
This can be shared by multiple FShaders with identical compiled output.
end note 



class FVertexFactory{
    +static void ModifyCompilationEnvironment(const FVertexFactoryShaderPermutationParameters& Parameters, FShaderCompilerEnvironment& OutEnvironment )
}
FShaderResource<|--FVertexFactory

note top
Encapsulates a vertex data source which can be linked into a vertex shader.
end note 



class  FShader{
    -TRefCountPtr<FShaderResource> Resource
}
note top
A compiled shader and its parameter bindings.
end note 



class FGlobalShader 
FShader<|--FGlobalShader

note top
Global shaders derive from this class to set their default recompile group as a global one
end note 




FShader--> FShaderResource



@enduml