@startuml Slate
!include SlateCore.pu
!include ApplicationCore.pu


class FSlateApplication{
	+ TSharedRef<FGenericWindow> FSlateApplication::MakeWindow( TSharedRef<SWindow> InSlateWindow, const bool bShowImmediately )
}
FSlateApplicationBase <|-- FSlateApplication 
FGenericApplicationMessageHandler <|-- FSlateApplication


FSlateApplication ..> SWindow




class SBorder{
}
note top
A border is an widget that can be used to contain other widgets.
It has a BorderImage property, which allows it to take on different appearances.
Border also has a Content() slot as well as some parameters controlling the
arrangement of said content.
end note
SCompoundWidget<|-- SBorder



class SButton
note top
Slate's Buttons are clickable Widgets that can contain arbitrary widgets as its Content()
end note
SBorder<|-- SButton















@enduml