@startuml

!startsub Slate

!include Engine.pu
!include ApplicationCore.pu
!include plugins.pu
!include RenderCore.pu
!include Renderer.pu
!include RHI.pu
!include Slate.pu


!endsub



























SWindow --o FGenericWindow



FSlateApplication ..> FGenericWindow



@enduml